server:
  port: 9999

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 969220749279-fhocrc4hmpm138tanbgv4dun7ve34ir8.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri:
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  datasource:
    url: jdbc:postgresql://localhost:5432/thebook1
    username: postgres
    password: 123123 #Thay đổi ở máy mỗi người
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: duynkce171003@fpt.edu.vn
    password: u m i d k i j d u c b t b z p o
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  web:
    resources:
      static-locations: classpath:/static/
jwt:
  signerKey: "CYXfKCsUaBwDgqbbZJ8iv5Xz8muv+o3DdfrFZkc/x39KcUfRVkaE00anvOVDkgy4"
  valid-duration: 8640  # 1 ngay
  refreshable-duration: 86400 # 1 tuan

sms:
 key: "8rHmonzVEr9JuCHhfxDxt71rFb12L_h3"
 device: "df88a66e8fcfb6e2"

upload:
  path: "/Users/khanhduy/Desktop/Project_Spring/fshop/src/main/resources/static/avatars" #Thay đổi ở máy mỗi người
path:
  avatar: "http://localhost:9999/avatars/"

